## The Web Scraping Recipe

To scrape information from the web is:
1. **MAPPING**: Finding URLs of the pages containing the information you want.
2. **DOWNLOAD**: Fetching the pages via HTTP.
3. **PARSE**: Extracting the information from HTML.  
  
  
You could also add `connection`, `storing`, `logging`, etc.
   


### Packages used
Today we will mainly build on the python skills you have gotten so far, and tomorrow we will look into more specialized packages.

* for connecting to the internet we use: **requests**
* for parsing: **beautifulsoup** and **regex**
* for automatic browsing / screen scraping: **selenium** 
* for mitigating errors we use: **time**

We will write our scrapers with basic python, for larger projects consider looking into the packages **scrapy**

In [42]:
import pandas as pd
import numpy as np
import seaborn as sns
import yfinance as yf
import os

In [43]:
import requests
from bs4 import BeautifulSoup
import re
import selenium
import time

import tqdm
import os
import json

In [45]:
# NBA网站
url = 'https://www.basketball-reference.com/leagues/NBA_2018.html' # link to the website
dfs = pd.read_html(url) # parses all tables found on the page.
dfs[1]

         Western Conference   W   L   W/L%    GB   PS/G   PA/G   SRS
0          Houston Rockets*  65  17  0.793     —  112.4  103.9  8.21
1    Golden State Warriors*  58  24  0.707   7.0  113.5  107.5  5.79
2   Portland Trail Blazers*  49  33  0.598  16.0  105.6  103.0  2.60
3    Oklahoma City Thunder*  48  34  0.585  17.0  107.9  104.4  3.42
4                Utah Jazz*  48  34  0.585  17.0  104.1   99.8  4.47
5     New Orleans Pelicans*  48  34  0.585  17.0  111.7  110.4  1.48
6        San Antonio Spurs*  47  35  0.573  18.0  102.7   99.8  2.89
7   Minnesota Timberwolves*  47  35  0.573  18.0  109.5  107.3  2.35
8            Denver Nuggets  46  36  0.561  19.0  110.0  108.5  1.57
9      Los Angeles Clippers  42  40  0.512  23.0  109.0  109.0  0.15
10       Los Angeles Lakers  35  47  0.427  30.0  108.1  109.6 -1.44
11         Sacramento Kings  27  55  0.329  38.0   98.8  105.8 -6.60
12         Dallas Mavericks  24  58  0.293  41.0  102.3  105.4 -2.70
13        Memphis Grizzlies  22  60  0.268  43.0   99.3  105.5 -5.81
14             Phoenix Suns  21  61  0.256  44.0  103.9  113.3 -8.80

In [46]:
url = 'https://www.basketball-reference.com/leagues/NBA_2018.html'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')
soup.find_all('h2')[0].text

'Conference Standings'

In [47]:
# Mapping exercise - 招聘网站
links = []
for page in range(1,6,1):
    url = f'https://www.jobindex.dk/jobsoegning?page={page}'
    links.append(url)
links

['https://www.jobindex.dk/jobsoegning?page=1',
 'https://www.jobindex.dk/jobsoegning?page=2',
 'https://www.jobindex.dk/jobsoegning?page=3',
 'https://www.jobindex.dk/jobsoegning?page=4',
 'https://www.jobindex.dk/jobsoegning?page=5']

In [48]:
response = requests.get('https://www.jobindex.dk/jobsoegning?page=1', headers={'name':'Siyi','email':'wasariii@outlook.com'})
list_htmls = []
for url in tqdm.tqdm(links): #Track the time left before completing the loop
    response = requests.get(url)
    html = response.text
    list_htmls.append(html)
    time.sleep(0.5) #Sleep for 0.5 seconds

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.21s/it]

#### Log your activities

In [49]:
# Define the log function to gather the log information
def log(response,logfile,output_path=os.getcwd()):
    # Open or create the csv file
    if os.path.isfile(logfile): #If the log file exists, open it and allow for changes     
        log = open(logfile,'a')
    else: #If the log file does not exist, create it and make headers for the log variables
        log = open(logfile,'w')
        header = ['timestamp','status_code','length','output_file']
        log.write(';'.join(header) + "\n") #Make the headers and jump to new line
        
    # Gather log information
    status_code = response.status_code #Status code from the request result
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())) #Local time
    length = len(response.text) #Length of the HTML-string
    
    # Open the log file and append the gathered log information
    with open(logfile,'a') as log:
        log.write(f'{timestamp};{status_code};{length};{output_path}' + "\n") #Append the information and jump to new line

In [50]:
#写入log文件
list_htmls = []
logfile = 'log.csv'
for url in tqdm.tqdm(links):
    response = requests.get(url)
    html = response.text
    list_htmls.append(html)
    time.sleep(0.5)
    log(response,logfile)

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.18s/it]

In [51]:
list_htmls = []
for url in tqdm.tqdm(links):
    try:
        response = requests.get(url)
    except Exception as e:
        print(url) #Print url
        print(e) #Print error
        with open("list_htmls", "w") as l: #Save the list_htmls as a json file to retrieve at another time
            json.dump(list_htmls, l)
        continue #Continue to next iteration of the loop
    html = response.text
    list_htmls.append(html)
    time.sleep(0.5) #Sleep for 0.5 seconds

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.14s/it]

In [52]:

response = requests.get('https://www.boligsiden.dk/tilsalg', headers={'name':'Siyi','email':'wasariii@outlook.com'})
list_htmls = []
for url in tqdm.tqdm(links): #Track the time left before completing the loop
    response = requests.get(url)
    html = response.text
    list_htmls.append(html)
    time.sleep(0.5) #Sleep for 0.5 seconds

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.16s/it]

In [53]:
response = requests.get('https://api.prod.bs-aws-stage.com/search/cases?addressTypes=villa%2Ccondo%2Cterraced+house%2Choliday+house%2Ccooperative%2Cfarm%2Chobby+farm%2Cfull+year+plot%2Cvilla+apartment%2Choliday+plot&per_page=50&page=1&highlighted=true&sortAscending=true&sortBy=timeOnMarket')
result = response.json()

result_properties = result['cases']
data = pd.DataFrame(result_properties)
data

,_links,address,addressType,caseID,caseUrl,coordinates,daysOnMarket,defaultImage,descriptionBody,descriptionTitle,...,realEstate,realtor,slug,status,totalClickCount,totalFavourites,weightedArea,yearBuilt,lotArea,basementArea
0,{'self': {'href': '/cases/02f5c770-36c7-4add-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,02f5c770-36c7-4add-aca9-ef1f1cc1b3ff,http://www.paulun.dk/bolig-redirect?mgl=2640&s...,"{'lat': 55.66615, 'lon': 12.617624, 'type': 'E...",1,"{'imageSources': [{'size': {'height': 80, 'wid...",Rigtig god beliggenhed! Lejligheden er beligge...,INDFLYTNINGSKLAR 2-VÆRELSET MED SUPER BELIGGEN...,...,"{'downPayment': 150000, 'grossMortgage': 14684...",{'_links': {'self': {'href': '/realtors/0f76bb...,bremensgade-23-2-tv-2300-koebenhavn-s-01010828...,open,173,2,55.00,1939,NaN,NaN
1,{'self': {'href': '/cases/09777162-a79c-4c13-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,09777162-a79c-4c13-aafa-697c772fb16f,https://www.realmaeglerne.dk/301-redirect/?mgl...,"{'lat': 55.126675, 'lon': 12.064598, 'type': '...",2,"{'imageSources': [{'size': {'height': 80, 'wid...",4-V ejerlejlighed opført som et rækkehus og pe...,1. RÆKKE TIL FJORDEN - INDFLYTNINGSKLART,...,"{'downPayment': 105000, 'grossMortgage': 10644...",{'_links': {'self': {'href': '/realtors/e799ab...,kirsebaervej-34-4720-praestoe-03900761__34_______,open,562,1,98.00,1981,3431.0,NaN
2,{'self': {'href': '/cases/9724f5da-480e-45ef-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,terraced house,9724f5da-480e-45ef-8065-a17274fbe24f,http://www.nybolig.dk/maegler/pages/property-p...,"{'lat': 55.30157, 'lon': 11.540407, 'type': 'E...",2,"{'imageSources': [{'size': {'height': 80, 'wid...",Drømmer I om et dejligt hus med en god beligge...,Velindrettet halvt dobbelthus i Fuglebjerg,...,"{'downPayment': 65000, 'grossMortgage': 6553, ...",{'_links': {'self': {'href': '/realtors/cb08f4...,dalsgaardsvej-2-4250-fuglebjerg-03700249___2__...,open,129,0,103.20,1980,618.0,NaN
3,{'self': {'href': '/cases/bef77f06-1be8-4149-9...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,bef77f06-1be8-4149-9966-c50a5ed57faf,https://home.dk/sag/6210000652,"{'lat': 56.302917, 'lon': 9.590847, 'type': 'E...",2,"{'imageSources': [{'size': {'height': 80, 'wid...","I roligt lukket kvarter, tæt ved masser af nat...",Velbeliggende i roligt attraktivt kvarter,...,"{'downPayment': 75000, 'grossMortgage': 7361, ...",{'_links': {'self': {'href': '/realtors/c18587...,solsortevej-37-8643-ans-by-07401660__37_______,open,209,2,133.90,1978,961.0,NaN
4,{'self': {'href': '/cases/8dcc6f60-57c2-4daa-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,8dcc6f60-57c2-4daa-ba12-343ec30c83e1,https://www.danbolig.dk?propertyid=2690000038&...,"{'lat': 55.374687, 'lon': 10.363591, 'type': '...",2,"{'imageSources': [{'size': {'height': 80, 'wid...",Velkommen til Rosenvænget 23 – et rigtig dejli...,"Skønne rammer, masser af plads og dejlig belig...",...,"{'downPayment': 275000, 'grossMortgage': 28102...",{'_links': {'self': {'href': '/realtors/5ddfef...,rosenvaenget-23-5250-odense-sv-04616723__23___...,open,684,3,294.45,1948,612.0,128.0
5,{'self': {'href': '/cases/fd5bf741-560c-41ec-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,fd5bf741-560c-41ec-bc23-b0cdd5db8703,https://www.danbolig.dk?propertyid=0140000547&...,"{'lat': 55.71455, 'lon': 11.739444, 'type': 'E...",2,"{'imageSources': [{'size': {'height': 80, 'wid...",En omfattende renovering har forvandlet denne ...,Renoveret villa med attraktiv underetage,...,"{'downPayment': 190000, 'grossMortgage': 19462...",{'_links': {'self': {'href': '/realtors/ea7520...,munkholmvej-105-4300-holbaek-03161036_105_______,open,468,1,140.90,1913,631.0,64.0
6,{'self': {'href': '/cases/7a564b33-eb4f-43fc-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,terraced house,7a564b33-eb4f-43fc-b008-4574d14c8347,https://www.danbolig.dk?propertyid=0140000619&...,"{'lat': 55.713028, 'lon': 11.730439, 'type': '...",2,"{'imageSources': [{'size': {'height': 80, 'wid...","I et roligt kvarter midt i Holbæk, tæt på grøn...",Yderst velholdt rækkehus centralt i Holbæk,...,"{'downPayment': 140000, 'grossMortgage': 14108...",{'_links': {'self': {'href': '/realtors/ea7520...,alfred-hansens-have-12-4300-holbaek-03160035__...,open,160,0,94.10,2004,96.0,NaN
7,{'self': {'href': '/cases/6f770ac3-9c6f-4737-8...,{'_links': {'self': {'href': '/addresses/71dbc...,villa,6f770ac3-9c6f-4737-86ce-c3f9e1299d97,http://www.nybolig.dk/maegler/pages/property-p...,"{'lat': 55.76669, 'lon': 9.543022, 'type': 'EP...",2,"{'imageSources': [{'size': {'height': 80, 'wid...","Denne moderne villa har mange kvaliteter, og m...",NaN,...,"{'downPayment': 165000, 'grossMortgage': 16644...",{'_links': {'self': {'href': '/realtors/134128...,niels-bisteds-vej-1-7100-vejle-06303014___1___...,open,337,3,165.00,2015,1027.0,NaN
8,{'self': {'href': '/cases/44253f24-a3f5-4f92-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,44253f24-a3f5-4f92-a6fe-6764f8eef8a9,https://www.kleinadamsen.dk/bolig/havdrup-4622...,"{'lat': 55.54057, 'lon': 12.116872, 'type': 'E...",3,"{'imageSources': [{'size': {'height': 80, 'wid...",Lige på hjørnet af Vinkelvej og Hovedgaden fin...,Charmerende villa fra 1897.,...,"{'downPayment': 150000, 'grossMortgage': 14181...",{'_links': {'self': {'href': '/realtors/466c3a...,hovedgaden-42-4622-havdrup-02692777__42_______,open,153,2,129.60,1897,506.0,NaN
9,{'self': {'href': '/cases/e5ec3c73-24f8-47f7-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,e5ec3c73-24f8-47f7-a92d-0cebb5ef52f9,https://www.danbolig.dk?propertyid=0140000584&...,"{'lat': 55.669468, 'lon': 11.76874, 'type': 'E...",3,"{'imageSources': [{'size': {'height': 80, 'wid...",Glæd jer til at udforske denne rummelige villa...,Stor familievilla på i alt 270 m2 - i Arnakke ...,...,"{'downPayment': 145000, 'grossMortgage': 14592...",{'_links': {'self': {'href': '/realtors/ea7520...,arnakkegaards-alle-7-4390-vipperoed-03160062__...,open,175,0,195.50,1973,876.0,135.0
10,{'self': {'href': '/cases/f4f2efd4-3f02-4407-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,f4f2efd4-3f02-4407-b6bf-e18aac66e217,https://www.danbolig.dk?propertyid=1770000180&...,"{'lat': 55.524612, 'lon': 12.1674, 'type': 'EP...",3,"{'imageSources': [{'size': {'height': 80, 'wid...",På Møllebakken 10 i Jersie kan I nu overtage n...,150 m2 villa med 100 m2 god kælder i skønt omr...,...,"{'downPayment': 215000, 'grossMortgage': 20862...",{'_links': {'self': {'href': '/realtors/9fe16d...,moellebakken-10-2680-solroed-strand-02695188__...,open,250,3,190.00,1967,844.0,100.0
11,{'self': {'href': '/cases/c7a3e8b0-8eca-432a-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,c7a3e8b0-8eca-432a-adf8-fd26e8539972,https://www.danbolig.dk?propertyid=0350000205&...,"{'lat': 55.845303, 'lon': 12.43989, 'type': 'E...",3,"{'imageSources': [{'size': {'height': 80, 'wid...",Vandtårnsvej ligger centralt i nærheden af bym...,Charme og selvtillid ved Rude Skov!,...,"{'downPayment': 390000, 'grossMortgage': 39884...",{'_links': {'self': {'href': '/realtors/3c9ae3...,vandtaarnsvej-10-3460-birkeroed-02300682__10__...,open,521,1,217.10,1950,993.0,69.0
12,{'self': {'href': '/cases/4632e9ad-317f-45bc-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,4632e9ad-317f-45bc-a24c-f9a646a0a4e9,https://www.danbolig.dk?propertyid=0350000305&...,"{'lat': 55.83866, 'lon': 12.4127, 'type': 'EPS...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Lejligheden er beliggende i et eftertragtet om...,"Indbydende, lys lejlighed i Birkerød",...,"{'downPayment': 110000, 'grossMortgage': 11283...",{'_links': {'self': {'href': '/realtors/3c9ae3...,lyngborghave-2b-2-th-3460-birkeroed-02300393__...,open,169,0,72.00,1975,NaN,NaN
13,{'self': {'href': '/cases/aa8ad55c-9b55-4308-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,aa8ad55c-9b55-4308-8e4f-b500e153280a,https://www.danbolig.dk?propertyid=0350000290&...,"{'lat': 55.859886, 'lon': 12.428505, 'type': '...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Få skridt fra Sjælsø og Eskemose Skov ligger d...,Stor familievilla ved Sjælsø,...,"{'downPayment': 390000, 'grossMortgage': 38204...",{'_links': {'self': {'href': '/realtors/3c9ae3...,groendalsvaenge-3b-3460-birkeroed-02300218__3b...,open,324,0,180.25,1984,920.0,NaN
14,{'self': {'href': '/cases/30fc8339-20fb-49f8-9...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,30fc8339-20fb-49f8-9c19-ad85c3069e21,http://www.paulun.dk/bolig-redirect?mgl=2640&s...,"{'lat': 55.664898, 'lon': 12.616044, 'type': '...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",I rolige omgivelser i Holmbladskvarteret på Am...,Velindrettet 2V’er med altan i hjertet af Amager,...,"{'downPayment': 160000, 'grossMortgage': 15402...",{'_links': {'self': {'href': '/realtors/0f76bb...,hessensgade-23-1-th-2300-koebenhavn-s-01012872...,open,150,1,57.00,1965,NaN,NaN
15,{'self': {'href': '/cases/63471ef0-e88c-4f6b-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,63471ef0-e88c-4f6b-a497-1198b0b5ed41,http://www.boligone.dk/sag.aspx?mgl=2737&sagsn...,"{'lat': 56.362865, 'lon': 8.602472, 'type': 'E...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Huset på Lemvigvej 43 er på 76 kvm boligareal ...,Hus med god garage på Lemvigvej,...,"{'downPayment': 50000, 'grossMortgage': 5247, ...",{'_links': {'self': {'href': '/realtors/e4e453...,lemvigvej-43-7500-holstebro-06613673__43_______,open,346,1,84.75,1917,788.0,NaN
16,{'self': {'href': '/cases/8c50a8fb-fa6e-457c-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,8c50a8fb-fa6e-457c-8fbe-312f8bb7dfdc,https://www.danbolig.dk?propertyid=0350000052&...,"{'lat': 55.852978, 'lon': 12.434475, 'type': '...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Vi er glade for at kunne præsentere måske Birk...,Smukt og stilrent istandsat!,...,"{'downPayment': 110000, 'grossMortgage': 11266...",{'_links': {'self': {'href': '/realtors/3c9ae3...,byagervej-139-1-tv-3460-birkeroed-02300076_139...,open,192,4,71.00,1959,NaN,NaN
17,{'self': {'href': '/cases/09451fe8-1e71-4621-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,09451fe8-1e71-4621-a600-eaddee9c5c18,https://www.danbolig.dk?propertyid=0350000218&...,"{'lat': 55.850597, 'lon': 12.417173, 'type': '...",4,"{'imageSources': [{'size': {'height': 80, 'wid...","Her er tale om en extraordinær, rummelig og in...",Flot og moderne villa til den store familie!,...,"{'downPayment': 350000, 'grossMortgage': 34371...",{'_links': {'self': {'href': '/realtors/3c9ae3...,vestervang-14-3460-birkeroed-02300713__14_______,open,340,1,141.00,1959,1019.0,NaN
18,{'self': {'href': '/cases/32d465f7-b4c6-437e-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,32d465f7-b4c6-437e-8730-d3c2130de09e,https://www.lm-bolig.dk/sag.aspx?mgl=2245&sags...,"{'lat': 55.65732, 'lon': 12.410391, 'type': 'E...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Orker du ikke sætte i stand er denne lejlighed...,Indflytningsklar 3 vær. lys lejlighed!,...,"{'downPayment': 110000, 'grossMortgage': 10798...",{'_links': {'self': {'href': '/realtors/df9a43...,broendbyvestervej-68b-1-1-2605-broendby-015300...,open,185,0,82.00,1967,NaN,NaN
19,{'self': {'href': '/cases/a709c38d-7c79-415f-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,holiday house,a709c38d-7c79-415f-ab95-7b8829c339db,https://www.f-bolig.dk/sag.aspx?mgl=2557&sagsn...,"{'lat': 55.92513, 'lon': 11.931143, 'type': 'E...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Godt beliggende fritidshus på 79 m2 på utrolig...,"Dejligt fritidshus på 79 m2, heraf gæstehus på...",...,"{'downPayment': 65000, 'grossMortgage': 6623, ...",{'_links': {'self': {'href': '/realtors/00b381...,skovsneppevej-39-3630-jaegerspris-02501098__39...,open,536,5,49.50,1969,1232.0,NaN
20,{'self': {'href': '/cases/fe6e4b6e-c22c-4f97-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,fe6e4b6e-c22c-4f97-80f9-452a3eabc0a5,http://www.nybolig.dk/maegler/pages/property-p...,"{'lat': 55.23187, 'lon': 11.730272, 'type': 'E...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",Nu kan I overtage nøglerne til denne flotte vi...,Flot etplansvilla med fantastisk have i Digter...,...,"{'downPayment': 150000, 'grossMortgage': 15216...",{'_links': {'self': {'href': '/realtors/cb08f4...,leif-panduros-vej-50-4700-naestved-03700952__5...,open,633,1,134.90,2004,746.0,NaN
21,{'self': {'href': '/cases/2bd381cc-06a2-412a-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,2bd381cc-06a2-412a-8a64-1b8d46392344,https://www.danbolig.dk?propertyid=0350000286&...,"{'lat': 55.829956, 'lon': 12.427377, 'type': '...",4,"{'imageSources': [{'size': {'height': 80, 'wid...",I særdeles velholdt bebyggelse med god ejerfor...,Velholdt 3 værelses med have,...,"{'downPayment': 105000, 'grossMortgage': 10799...",{'_links': {'self': {'href': '/realtors/3c9ae3...,bistrup-park-43-3460-birkeroed-02300052__43___...,open,153,0,72.00,1960,NaN,NaN
22,{'self': {'href': '/cases/5f90e2f8-596b-4aee-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,5f90e2f8-596b-4aee-8c9e-0b731b3d2bbe,https://www.bbshorsens.dk/detail/5fda7a06-b200...,"{'lat': 55.964684, 'lon': 9.752644, 'type': 'E...",4,"{'imageSources': [{'size': {'height': 80, 'wid...","Her, centralt i Østbirk, finder vi dette indfl...",Fint og indbydende byhus,...,"{'downPayment': 55000, 'grossMortgage': 5218, ...",{'_links': {'self': {'href': '/realtors/538168...,storegade-52-8752-oestbirk-06150536__52_______,open,148,1,168.50,1945,677.0,92.0
23,{'self': {'href': '/cases/5141ca8f-bebc-40b8-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,condo,5141ca8f-bebc-40b8-a327-9fc90a0ae7c2,https://www.realmaeglerne.dk/301-redirect/?mgl...,"{'lat': 55.396782, 'lon': 10.34828, 'type': 'E...",6,"{'imageSources': [{'size': {'height': 80, 'wid...",Nu har du chancen for at erhverve dig dette sk...,VELINDRETTET OG MODERNISERET EJERLEJLIGHED OPF...,...,"{'downPayment': 70000, 'grossMortgage': 7090, ...",{'_links': {'self': {'href': '/realtors/afc4c7...,hoejstrupvangen-16-5200-odense-v-04613749__16_...,open,347,2,60.00,1979,NaN,NaN
24,{'self': {'href': '/cases/1819e10e-33f9-43f7-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,1819e10e-33f9-43f7-8a6d-847d10f88135,https://home.dk/sag/1440000916,"{'lat': 55.641994, 'lon': 12.074386, 'type': '...",7,"{'imageSources': [{'size': {'height': 80, 'wid...",Selvom denne klassiske villa i Roskilde er kla...,Rummelig villa med plads til egne idéer,...,"{'downPayment': 590000, 'grossMortgage': 57914...",{'_links': {'self': {'href': '/realtors/ede568...,villavej-7-4000-roskilde-02659218___7_______,open,1341,2,257.25,1932,1104.0,99.0
25,{'self': {'href': '/cases/6f4d6f4c-f049-43dc-a...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,6f4d6f4c-f049-43dc-ad07-e3aa19348621,https://www.danbolig.dk?propertyid=0140000351&...,"{'lat': 55.79912, 'lon': 11.442718, 'type': 'E...",7,"{'imageSources': [{'size': {'height': 80, 'wid...",Drømmer I om at vågne op med udsigt til de åbn...,Velholdt familievilla med skøn udsigt i Fårevejle,...,"{'downPayment': 85000, 'grossMortgage': 8727, ...",{'_links': {'self': {'href': '/realtors/ea7520...,pilevej-20-4540-faarevejle-03061770__20_______,open,470,5,154.00,1901,3022.0,NaN
26,{'self': {'href': '/cases/cb4ece1b-4fcc-4334-8...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,cb4ece1b-4fcc-4334-8bb9-c1cb862f9a8c,https://www.danbolig.dk?propertyid=2840000171&...,"{'lat': 55.404167, 'lon': 11.380798, 'type': '...",7,"{'imageSources': [{'size': {'height': 80, 'wid...",Hvad siger I til at få det perfekte begynderhu...,Fin villa med sydvendt have og central beligge...,...,"{'downPayment': 70000, 'grossMortgage': 6873, ...",{'_links': {'self': {'href': '/realtors/8d26cf...,klosterbanken-68-4200-slagelse-03300878__68___...,open,907,6,106.20,1964,842.0,28.0
27,{'self': {'href': '/cases/efe152ae-03ae-4d92-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,efe152ae-03ae-4d92-b7a4-0430417c79ba,https://home.dk/sag/6210000671,"{'lat': 56.374954, 'lon': 9.626576, 'type': 'E...",7,"{'imageSources': [{'size': {'height': 80, 'wid...","I roligt og børnevenligt boligområde, finder d...",Velholdt etplans villa med god planløsning,...,"{'downPayment': 85000, 'grossMortgage': 7997, ...",{'_links': {'self': {'href': '/realtors/c18587...,nedermarken-9-8850-bjerringbro-07911066___9___...,open,305,0,139.10,1980,1003.0,NaN
28,{'self': {'href': '/cases/e318b37e-16f2-4d92-9...,{'_links': {'self': {'href': '/addresses/0a3f5...,holiday house,e318b37e-16f2-4d92-9d41-9493da5dc797,https://www.robinhus.dk/redirect/?caseno=HAN-0...,"{'lat': 55.55089, 'lon': 11.161537, 'type': 'E...",8,"{'imageSources': [{'size': {'height': 80, 'wid...",Super dejligt fritidshus ved Bjerge Sydstrand....,Super dejligt fritidshus ved Bjerge Sydstrand.,...,"{'downPayment': 115000, 'grossMortgage': 11413...",{'_links': {'self': {'href': '/realtors/6c8311...,fredskovens-engvej-1-4480-store-fuglede-032604...,open,783,6,117.45,2004,2400.0,5.0
29,{'self': {'href': '/cases/ffaf5342-a4b5-4d97-a...,{'_links': {'self': {'href': '/addresses/0ab7a...,condo,ffaf5342-a4b5-4d97-a229-7c9f6e7b2764,http://www.nybolig.dk/maegler/pages/property-p...,"{'lat': 55.666405, 'lon': 12.582442, 'type': '...",8,"{'imageSources': [{'size': {'height': 80, 'wid...",På en unik beliggenhed væk fra støj og larm; g...,BLANDING AF PENTHOUSE OG BYHUS ROLIGT OG ATTRA...,...,"{'downPayment': 525000, 'grossMortgage': 52657...",{'_links': {'self': {'href': '/realtors/c8abf1...,weidekampsgade-47-2-3-2300-koebenhavn-s-010181...,open,1674,8,130.00,2007,NaN,NaN
30,{'self': {'href': '/cases/726d3ceb-52d3-4bd9-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,726d3ceb-52d3-4bd9-b963-6806c7f29567,http://www.boligone.dk/sag.aspx?mgl=2737&sagsn...,"{'lat': 56.34523, 'lon': 8.342526, 'type': 'EP...",8,"{'imageSources': [{'size': {'height': 80, 'wid...","På hovedgaden i Vemb, tæt på centrum, indkøbsm...","Central beliggende byhus i Vemb, med stor grund",...,"{'downPayment': 30000, 'grossMortgage': 2603, ...",{'_links': {'self': {'href': '/realtors/e4e453...,noerregade-39-7570-vemb-06610834__39_______,open,124,0,209.55,1910,1114.0,18.0
31,{'self': {'href': '/cases/e7950956-8ee7-4035-b...,{'_links': {'self': {'href': '/addresses/dcd64...,terraced house,e7950956-8ee7-4035-b157-c2bef2e9972f,https://www.danbolig.dk?propertyid=0140000609&...,"{'lat': 55.714474, 'lon': 11.620679, 'type': '...",8,"{'imageSources': [{'size': {'height': 80, 'wid...","På Tømrergårdsvej 3 i Tuse, en lille, men yder...",Moderne og flot rækkehus i Tuse,...,"{'downPayment': 140000, 'grossMortgage': 13779...",{'_links': {'self': {'href': '/realtors/ea7520...,toemrergaardsvej-3-4300-holbaek-03162205___3__...,open,732,0,NaN,2021,187.0,NaN
32,{'self': {'href': '/cases/ecf4cd0f-7682-4bb3-b...,{'_links': {'self': {'href': '/addresses/58c7f...,villa,ecf4cd0f-7682-4bb3-b7fb-b8d85d6dc448,https://www.danbolig.dk?propertyid=2840000127&...,"{'lat': 55.417, 'lon': 11.389807, 'type': 'EPS...",8,"{'imageSources': [{'size': {'height': 80, 'wid...",Bliv de heldige ejere af denne moderne villa f...,"Lækker, nybygget villa i fredeligt kvarter i S...",...,"{'downPayment': 280000, 'grossMortgage': 27487...",{'_links': {'self': {'href': '/realtors/8d26cf...,poppelvaenget-1-4200-slagelse-03302198___1_______,open,1086,4,NaN,2021,837.0,NaN
33,{'self': {'href': '/cases/91d140a9-97a7-4ac6-b...,{'_links': {'self': {'href': '/addresses/0a3f5...,villa,91d140a9-97a7-4ac6-b97a-c92abbb08b46,https://www.danbolig.dk?propertyid=2830000054&...,"{'lat': 55.538795, 'lon': 11.231526, 'type': '...",8,"{'imageSources': [{'size': {'height': 80, 'wid...",Den blinde vej Søndre Alle i Gørlev ligger ind...,Indflytningsklar villa på blind vej,...,"{'downPayment': 65000, 'grossMortgage': 6162, ...",{'_links': {'self': {'href': '/realtors/680887...,soendre-alle-4-4281-goerlev-03261760___4_______,open,133,1,112.00,1900,496.0,NaN

#### Exercise

In [54]:
links = []
for offset in range(0,5*20,20):
    url = f'https://job.jobnet.dk/CV/FindWork/Search?offset={offset}'   # 关注Fetch/XHR中最长的一条，然后找到它的Request URL
    links.append(url)
    
logfile = 'log3.csv'
list_htmls = []
jobs_first100 = pd.DataFrame()

for url in tqdm.tqdm(links):
    try:
        response = requests.get(url, headers={'name':'Siyi','email':'wasariii@outlook.com'})
    except Exception as e:
        print(url) #Print url
        print(e) #Print error
        jobs_first100.to_csv('jobs_first100.csv') #Save the dataframe as a csv file to retrieve at another time
        continue #Continue to next iteration of the loop
    
    if response.ok: #Check if the response carries any data
        result_json = response.json() #If the response carries data, then convert it to json format
    else: #If the response does not carry any data, then print the status_code and continue to next iteration of the loop
        print(response.status_code)
        continue
    
    result_df = pd.DataFrame(result_json['JobPositionPostings']) # 网页Network-Search-Preview下
    jobs_first100 = pd.concat([jobs_first100,result_df], axis=0, ignore_index=True) #Append to the rest of the data
    log(response, logfile)
    time.sleep(0.5) #Sleep for 0.5 seconds
jobs_first100

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.11it/s]

,AutomatchType,Abroad,Weight,Title,JobHeadline,Presentation,HiringOrgName,WorkPlaceAddress,WorkPlacePostalCode,WorkPlaceCity,...,HiringOrgCVR,UserLoggedIn,AnonymousEmployer,ShareUrl,DetailsUrl,JobLogUrl,HasLocationValues,ID,Latitude,Longitude
0,0,False,1.0,Næstkommanderende til Jægerkorpsets operative ...,Næstkommanderende til Jægerkorpsets operative ...,Kan du have mange bolde i luften samtidig med ...,Flyvestation Aalborg,Thisted Landevej 53,9430,Vadum,...,16287180,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5653185,https://job.jobnet.dk/CV/FindWork/Details/5653185,True,5653185,57.1085,9.8574
1,0,False,1.0,Frisk gut på 52 år søger handicaphjælper - Viborg,Frisk gut på 52 år søger handicaphjælper - Viborg,OMRÅDE: 8800 Viborg\nLIDT OM MIG:Jeg er en fr...,HANDICAPFORMIDLINGEN ApS,,8800,Viborg,...,34605416,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5653079,https://job.jobnet.dk/CV/FindWork/Details/5653079,True,5653079,56.4168,9.3690
2,0,False,1.0,Tilst Skole søger en engageret og faglig dygti...,Tilst Skole søger en engageret og faglig dygti...,Du skal have følgende profil:· Du har ...,Aarhus Kommune,Tåstumvænget 8,8381,Tilst,...,55133018,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5653184,https://job.jobnet.dk/CV/FindWork/Details/5653184,True,5653184,56.1895,10.1132
3,0,False,1.0,Pædagogmedhjælper til Snejbjerg Skoles SFO,Pædagogmedhjælper til Snejbjerg Skoles SFO,Snejbjerg Skole søger en 19-timers pædagogmedh...,Herning Kommune,Snejbjerg Hovedgade 75,7400,Herning,...,29189919,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5653071,https://job.jobnet.dk/CV/FindWork/Details/5653071,True,5653071,56.1283,8.8854
4,0,False,1.0,Børnehaveklasseassistent til Hedelyskolen,Børnehaveklasseassistent til Hedelyskolen,Hedelyskolen er en folkeskole med omkring 730 ...,Hedelyskolen,Drønnergårds Alle 30,2670,Greve,...,44023911,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5653069,https://job.jobnet.dk/CV/FindWork/Details/5653069,True,5653069,55.5410,12.3529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,False,1.0,Vi søger en socialrådgiver eller socialformidl...,Vi søger en socialrådgiver eller socialformidl...,Da en af vores dygtige rådgivere har søgt nye ...,"Center for Børn, Unge og Familier",Herlev Bygade 90,2730,Herlev,...,63640719,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5652944,https://job.jobnet.dk/CV/FindWork/Details/5652944,True,5652944,55.7251,12.4326
96,0,False,1.0,#JobsForUkraine: Cleaningassistant to Hedenst...,#JobsForUkraine: Cleaningassistant to Hedenst...,6 Hours per week\nYou can take the cleaning be...,Dansk Koncept Service A/S,,8722,Hedensted,...,27268021,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5652942,https://job.jobnet.dk/CV/FindWork/Details/5652942,True,5652942,55.7651,9.7113
97,0,False,1.0,#jobsForUkraine: Cleaning job in Billund Area...,#jobsForUkraine: Cleaning job in Billund Area...,\nEngelsk\nDo you like to clean? Then it´s YO...,Dansk Koncept Service A/S,,7190,Billund,...,27268021,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5652940,https://job.jobnet.dk/CV/FindWork/Details/5652940,True,5652940,55.7379,9.1007
98,0,False,1.0,Social- og sundhedshjælper til dag- og aftenva...,Social- og sundhedshjælper til dag- og aftenva...,Motiveres du af at yde en høj kvalitet af plej...,Københavns Kommune,Borups Allé 177,2400,København NV,...,64942212,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5653126,https://job.jobnet.dk/CV/FindWork/Details/5653126,True,5653126,55.6960,12.5253
99,0,False,1.0,Personlig hjælpere søges – 37 timer pr. uge i ...,Personlig hjælpere søges – 37 timer pr. uge i ...,LIDT OM MIG:Jeg er en moden mand som er kørest...,Handicapformidlingen Vildbjerg,,5500,Middelfart,...,34605416,False,False,https://job.jobnet.dk/CV/FindWork/DetailsSocia...,https://job.jobnet.dk/CV/FindWork/Details/5575870,https://job.jobnet.dk/CV/FindWork/Details/5575870,True,5575870,55.4893,9.7849

In [55]:
jobs_first100.groupby(jobs_first100['OccupationArea'])['ID'].count().sort_values(ascending=False)[0:10]

OccupationArea
Sundhed, omsorg og personlig pleje               20
Akademisk arbejde                                18
Pædagogisk, socialt og kirkeligt arbejde         16
Ledelse                                           7
Salg, indkøb og markedsføring                     6
Transport, post, lager- og maskinførerarbejde     6
Kontor, administration, regnskab og finans        5
Bygge og anlæg                                    4
Undervisning og vejledning                        4
Industriel produktion                             3
Name: ID, dtype: int64

# Parsing the HTML with BeautifulSoup
## Learning by doing: Creating a dataset from www.dr.dk/nyheder/udland

### Let's put together some of the stuff we have learned so far
1. **Mapping:** In this exercise we will collect some URLs from webpages with news articles and save them into a list
2. **Downloading:** Then we will download the HTML content of the webpages
3. **Parsing:** At last we will collect relevant information in each article

## 1. MAPPING

In [56]:
# Define our URL
url = 'https://www.dr.dk/nyheder/udland' 

# Connects to site
response = requests.get(url, headers={'name':'Siyi','email':'wasariii@outlook.com'})

# Parse data with BeautifulSoup
soup = BeautifulSoup(response.content,'lxml')

# Identify articles to scrape by inspecting site
articles = soup.find_all('div', class_ = 'dre-teaser-content') #(class_ is used because class is reserved in Python)

In [57]:
list_of_article_urls = []
# Creating a loop that appends the article url to the list above
for i in range(len(articles)):
    list_of_article_urls.append(articles[i].find('a')['href'])


list_of_article_urls_final = []
for link in list_of_article_urls:
    if '/nyheder/udland' in link: #All article URLs have this string in them, so we restrict on it being in the URL
        list_of_article_urls_final.append(link)
print(list_of_article_urls_final)

['/nyheder/udland/amerikansk-radiovaert-skal-betale-millionerstatning-loegne-om-skoleskyderi', '/nyheder/udland/ukrainsk-militaer-bryder-krigsregler-foerer-krig-fra-private-hjem-skoler-og', '/nyheder/udland/kina-laver-storstillet-militaeroevelse-omkring-taiwan-taiwan-goer-sig-klar-sig-til', '/nyheder/udland/drs-matilde-kimer-er-blevet-udvist-af-rusland', '/nyheder/udland/foerste-amerikanske-delstat-har-stemt-nej-til-fjerne-retten-til-fri-abort', '/nyheder/udland/pelosi-roser-taiwans-demokrati-mens-kina-sender-kampfly-paa-vingerne', '/nyheder/udland/taiwan-byder-pelosi-velkommen-med-aabne-arme-mens-kina-skruer-op-trusler', '/nyheder/udland/al-qaeda-leder-blev-draebt-i-diplomatkvarter-fem-minutters-gang-fra-tidligere-dansk', '/nyheder/udland/nancy-pelosi-trodser-kinesiske-advarsler-ankommer-til-taiwan-til-historisk-besoeg', '/nyheder/udland/corona-laeges-selvmord-saetter-gang-i-oestrigsk-debat-om-netchikane', '/nyheder/udland/puk-damsgaard-markant-og-bemaerkelsesvaerdigt-al-qaedas-draebte-topleder-opholdt-sig', '/nyheder/udland/usa-draeber-al-qaedas-leder-med-drone-i-kabul', '/nyheder/udland/foerste-fragtskib-i-flere-maaneder-sejler-nu-gennem-sortehavet-en-lettelse-verden', '/nyheder/udland/forventningerne-er-meget-lave-forud-verdens-stoerste-konference-nedrustning-af', '/nyheder/udland/der-spares-hvor-der-kan-eu-lande-lancerer-energibesparende-tiltag', '/nyheder/udland/drab-paa-nigeriansk-gadesaelger-ved-hoejlys-dag-udloeser-vrede-i-italien', '/nyheder/udland/nye-pas-sim-kort-og-tv-kanaler-putin-er-i-fuld-gang-med-indfoere-russiske-tilstande-i', '/nyheder/udland/corona-duks-har-pludselig-flere-doedsfald-end-nogensinde', '/nyheder/udland/rusland-vil-lade-fn-og-roede-kors-undersoege-angreb-paa-faengslede-krigsfanger', '/nyheder/udland/ukraine-bliver-kritiseret-sende-boern-med-handicap-paa-institutioner-det-minder-om-et', '/nyheder/udland/endnu-en-kinesisk-raket-styrter-mod-jorden-decideret-dumt-og-uansvarligt', '/nyheder/udland/usa-gaar-ind-i-produktionen-af-mikrochips-det-vil-i-hoej-grad-komme-dansk-erhvervsliv', '/nyheder/udland/det-er-uholdbart-russiske-turister-stroemmer-til-finland', '/nyheder/udland/retten-faelder-dom-i-spektakulaer-fodboldfruesag-det-er-rebekah-vardy', '/nyheder/udland/kinas-xi-jinping-advarer-biden-leg-ikke-med-ilden-naar-det-gaelder-taiwan', '/nyheder/udland/ukraine-bomber-vigtig-bro-og-gaar-til-modangreb', '/nyheder/udland/russisk-journalist-doemt-miskreditere-haer', '/nyheder/udland/i-kyiv-trodser-de-luftalarmer-og-udgangsforbud-kom-med-dr-til-raveparty', '/nyheder/udland/trump-tilbage-i-washington-foerste-gang-siden-han-forlod-det-hvide-hus-0', '/nyheder/udland/eu-lande-har-aftalt-bruge-15-procent-mindre-gas-men-de-er-ikke-pisket-til-det', '/nyheder/udland/gazprom-strammer-ifoelge-tyskland-skruen-uden-grund', '/nyheder/udland/risikoen-udvisning-til-rwanda-holder-ikke-migranter-fra-soege-mod-storbritannien', '/nyheder/udland/paven-undskylder-til-de-oprindelige-folk-i-canada-jeg-beder-ydmygt-om-tilgivelse', '/nyheder/udland/xiaoyus-familie-og-tusindvis-andre-er-den-kinesiske-boligdroem-en-bunke-ruiner', '/nyheder/udland/derfor-besynger-ukrainerne-nyt-missilsystem-den-russiske-fremrykning-er-gaaet-i-staa', '/nyheder/udland/russisk-restaurant-i-berlin-lagt-had-folk-sagde-de-ville-skyde-os', '/nyheder/udland/oak-fire-haerger-ved-yosemite-nationalpark-i-usa', '/nyheder/udland/rusland-beskyldes-angribe-havn-dagen-efter-kornaftale-det-er-selvfoelgelig-med-vilje', '/nyheder/udland/kornpriserne-falder-efter-ny-aftale-kommer-til-tage-toppen-af-foedevarekrisen', '/nyheder/udland/analyse-trump-udstilles-af-tilstaaelser-fra-naermeste-og-afsloerende-videoklip', '/nyheder/udland/premierministeren-har-sagt-op-praesidenten-oploeser-parlamentet-og-sender-italienerne', '/nyheder/udland/anden-kritiske-rapport-paa-en-uge-baadmigranter-bliver-efterladt-i-farlige', '/nyheder/udland/rusland-udvider-sine-militaere-maal-i-ukraine-men-intet-tyder-paa-de-har-kapaciteten', '/nyheder/udland/cia-direktoer-afviser-rygter-om-putins-helbred-saa-vidt-vi-ved-saa-er-han-faktisk', '/nyheder/udland/russisk-gas-flyder-igen-mod-europa-men-er-gaskrisen-afvaerget']

## 2. DOWNLOADING + 3. PARSING

In [58]:
# We want to extract title, lead and time posted from the articles

# Creatig empty list for the infomation we want to extract for every article
title_list = []
lead_list = []
time_list = []

for i in range(10): #len(list_of_article_urls)
    
    # This time we scrape for each news article in the url list we created before
    url = 'https://www.dr.dk' + list_of_article_urls_final[i] #The scraped links are relative, so we need to add the base url
    response = requests.get(url, headers={'name':'Siyi','email':'wasariii@outlook.com'})
    soup = BeautifulSoup(response.content,'lxml')
    
    # Append title to list
    temp = soup.find_all('h1')
    temp = temp[1]
    temp = temp.text.strip()
    title_list.append(temp)
    
    # Append lead to list
    temp = soup.find('p', class_='dre-article-title__summary')
    temp = temp.text.strip()
    lead_list.append(temp)

    # Append time posted to list
    temp = soup.find('time', class_='dre-byline__date')
    temp = temp['datetime']
    time_list.append(temp)

In [117]:
df = pd.DataFrame({'title':title_list, 'lead':lead_list, 'time':time_list})
df

,title,lead,time
0,Amerikansk radiovært skal betale millionerstat...,"Alex Jones har i årevis påstået, at massakren ...",2022-08-05T03:55:00+00:00
1,Ukrainsk militær bryder krigsregler - fører kr...,Amnesty International har undersøgt tre forske...,2022-08-04T11:48:00+00:00
2,Kina laver storstilet militærøvelse omkring Ta...,Kina er lige nu i gang med en af de mest omfat...,2022-08-04T08:52:00+00:00
3,DR's Matilde Kimer er blevet udvist af Rusland,Rusland slår hårdt ned på uafhængige medier og...,2022-08-03T16:29:00+00:00
4,Første amerikanske delstat har stemt 'nej' til...,Resultatet er en vigtigt sejr for tilhængere a...,2022-08-03T08:56:00+00:00
5,"Pelosi roser Taiwans demokrati, mens Kina send...",Den amerikanske toppolitikers uanmeldte besøg ...,2022-08-03T03:57:00+00:00
6,"Taiwan byder Pelosi velkommen med åbne arme, m...","USA skal støtte demokrati alle steder, skriver...",2022-08-02T18:53:00+00:00
7,Al-Qaeda-leder blev dræbt i diplomatkvarter - ...,Terrorleders tilstedeværelse midt i hovedstade...,2022-08-02T16:14:00+00:00
8,Nancy Pelosi trodser kinesiske advarsler: Anko...,Formanden for Repræsentanternes Hus er ankomme...,2022-08-02T14:52:00+00:00
9,Corona-læges selvmord sætter gang i østrigsk d...,"I flere byer blev der tændt lys for læge, der ...",2022-08-02T11:55:00+00:00

In [114]:
# what if we need the body?
url = 'https://www.dr.dk/nyheder/udland/gazprom-strammer-ifoelge-tyskland-skruen-uden-grund' 
response = requests.get(url, headers={'name':'Siyi','email':'wasariii@outlook.com'})
soup = BeautifulSoup(response.content,'lxml')
body = soup.find('div', class_ = 'dre-article-body')

'''
This body consists of both sections with text and figures. We want it all.
But sections and figures have different tags, so we cannot just use find_all to find all elements in the body.
Instead we can use .children. It finds all children of the element body:
'''

body_text = []
for child in body.children:
    body_text.append(child.text)
print(body_text)

['Gazprom halverer gasleverancerne til Europa via Nord Stream 1. Årsagen er ifølge selskabet vedligehold af en gasturbine. Den daglige gasforsyning via gasledningen vil fra onsdag morgen blive reduceret til 33 millioner kubikmeter, oplyser Gazprom.Det svarer til cirka 20 procent af den maksimale kapacitet, og det fremgår ikke, hvor længe den yderligt reducerede forsyning af gas vil stå på.', '', 'Den tyske regering anser den forklaringen om vedligeholdelse for at være opfundet til lejligheden.- Ifølge vores oplysninger er der ingen teknisk grund til en reduktion i leverancerne, siger en talskvinde for Finansministeriet og minister Robert Habeck til Frankfurter Allgemeine Zeitung.Tyskerne får 25 procent af deres energi fra gas, hvor en overvejende del er kommet fra Rusland.Gasprisen stiger med 10 procentDet er anden gang indenfor en uge, at Gazprom reducerer leverancen af gas under påskud af reperation af gasturbiner. Da Gazprom efter ti dages vedligehold i sidste uge genåbnede for gasforsyningen til Tyskland, var meldingen, at der dagligt ville blive leveret cirka 67 millioner kubikmeter.Gazproms seneste melding betyder altså, at leverancerne til Europa bliver omtrent halveret fra onsdag. Gasledningen kan, når den kører for fuld kraft, levere cirka 167 millioner kubikmeter gas om dagen.', 'Nordstream 1-faciliter i Lubmin i Tyskland. (Arkiv) (Foto:\xa0HANNIBAL HANSCHKE ©\xa0Ritzau Scanpix)', 'Den ledende europæiske gaspris er mandag aften steget med op til ti procent efter udmeldingen fra Gazprom. Det er fjerde dag i træk, at gasprisen stiger, skriver finansmediet Marketwire ifølge Rtizau.Nord Stream 1 transporterer normalt hvert år 55 milliarder kubikmeter gas fra Rusland til Tyskland under Østersøen. Det er nok til at forsyne cirka 26 millioner europæiske hjem.Den tyske formand for det føderale agentur for digitalisering, klimaneutralitet og modstandsdygtighed, Klaus Müller, bekræfter, at den nuværende levering halveres fra onsdag.', '', 'Stormagter i Europa har anklaget Rusland for at bruge gas som et afpresningsmiddel over for Europa, fordi EU har indført sanktioner mod Rusland på grund af krigen i Ukraine. Ifølge Tyskland er der "ingen tekniske grunde" til den reducerede gasforsyning fra Nord Stream 1, som Gazprom ellers hævder.380.000 danske husstande benytter ifølge Energistyrelsen naturgas til opvarmning via gasfyr. Det svarer til ca. 800.000 danskere.', '', 'Tyskerne vender sig tilbage mod kulTyskland er blandt de europæiske lande, der er mest afhængig af den russiske gas. Men også flere andre europæiske lande, for eksempel Italien, er storforbrugere af gas, der kommer til Europa via Nord Stream 1.Rusland er verdens største eksportør af naturgas. Europa importerer omkring 40 procent af sin gas fra Rusland gennem Tyskland, som sender den billige russiske gas videre til øvrige dele af Europa.Nord Stream 1 er en 1.224 kilometer lang gasrørledning, som løber fra Rusland til Tyskland under Østersøen. Den har været i brug siden 2011.Gaskrisen har fået Tyskland til desperat at lede efter alternativer til gas til landets vigtige industri men også til private husholdninger. For eksempel ved at skifte over til den allermest forurenende energikilde. Nemlig kul. DR Nyheders korrespondent i Tyskland har været i Leipzig for at møde en kulhandler, der har kronede dage:', '', 'FAKTABOKS om Nord Stream 1•Nord Stream 1 er 1224 kilometer lang og består af to gasrørledninger, som løber under Østersøen.•De strækker sig fra Vyborg i Rusland til Lubmin i det nordøstlige Tyskland. Derfra transporteres gassen videre til øvrige dele af Europa.•Den har været i brug siden 2011 og har dermed i over et årti - indtil Ruslands krig mod Ukraine - været en pålidelig kilde til gas til Europa.•Den kan transportere 55 milliarder kubikmeter gas om året til Europa. Det er nok til at forsyne cirka 26 millioner europæiske hjem. Dermed er den særdeles vigtig for gasforsyningen til Europa.•Ruslands statsejede gasselskab Gazprom ejer 51 procent af Nord Stream 1. Tysklands EON og Wintershall Dea, hollandske Gasunie og Frankrigs Engie er også aktionærer.•Projektet er længe blevet set som en model for økonomisk samarbejde mellem Rusland og EU, hvor lande som Tyskland og Italien er blevet stærkt afhængige af den billige russiske gas.•Rusland er verdens største eksportør af naturgas. Europa importerer omkring 40 procent af sin gas fra Rusland.•Kilder: AFP og Reuters af /ritzau/']

In [61]:
'''
We have used .text to get the text of the HTML. The figure elements do not contain any text, so they will just be empty.
We can use .join() to join all the strings in the list. Just join it on an empty string:
# 这步似乎是只去掉了''
'''

''.join(body_text)

'Gazprom halverer gasleverancerne til Europa via Nord Stream 1. Årsagen er ifølge selskabet vedligehold af en gasturbine. Den daglige gasforsyning via gasledningen vil fra onsdag morgen blive reduceret til 33 millioner kubikmeter, oplyser Gazprom.Det svarer til cirka 20 procent af den maksimale kapacitet, og det fremgår ikke, hvor længe den yderligt reducerede forsyning af gas vil stå på.Den tyske regering anser den forklaringen om vedligeholdelse for at være opfundet til lejligheden.- Ifølge vores oplysninger er der ingen teknisk grund til en reduktion i leverancerne, siger en talskvinde for Finansministeriet og minister Robert Habeck til Frankfurter Allgemeine Zeitung.Tyskerne får 25 procent af deres energi fra gas, hvor en overvejende del er kommet fra Rusland.Gasprisen stiger med 10 procentDet er anden gang indenfor en uge, at Gazprom reducerer leverancen af gas under påskud af reperation af gasturbiner. Da Gazprom efter ti dages vedligehold i sidste uge genåbnede for gasforsyningen til Tyskland, var meldingen, at der dagligt ville blive leveret cirka 67 millioner kubikmeter.Gazproms seneste melding betyder altså, at leverancerne til Europa bliver omtrent halveret fra onsdag. Gasledningen kan, når den kører for fuld kraft, levere cirka 167 millioner kubikmeter gas om dagen.Nordstream 1-faciliter i Lubmin i Tyskland. (Arkiv) (Foto:\xa0HANNIBAL HANSCHKE ©\xa0Ritzau Scanpix)Den ledende europæiske gaspris er mandag aften steget med op til ti procent efter udmeldingen fra Gazprom. Det er fjerde dag i træk, at gasprisen stiger, skriver finansmediet Marketwire ifølge Rtizau.Nord Stream 1 transporterer normalt hvert år 55 milliarder kubikmeter gas fra Rusland til Tyskland under Østersøen. Det er nok til at forsyne cirka 26 millioner europæiske hjem.Den tyske formand for det føderale agentur for digitalisering, klimaneutralitet og modstandsdygtighed, Klaus Müller, bekræfter, at den nuværende levering halveres fra onsdag.Stormagter i Europa har anklaget Rusland for at bruge gas som et afpresningsmiddel over for Europa, fordi EU har indført sanktioner mod Rusland på grund af krigen i Ukraine. Ifølge Tyskland er der "ingen tekniske grunde" til den reducerede gasforsyning fra Nord Stream 1, som Gazprom ellers hævder.380.000 danske husstande benytter ifølge Energistyrelsen naturgas til opvarmning via gasfyr. Det svarer til ca. 800.000 danskere.Tyskerne vender sig tilbage mod kulTyskland er blandt de europæiske lande, der er mest afhængig af den russiske gas. Men også flere andre europæiske lande, for eksempel Italien, er storforbrugere af gas, der kommer til Europa via Nord Stream 1.Rusland er verdens største eksportør af naturgas. Europa importerer omkring 40 procent af sin gas fra Rusland gennem Tyskland, som sender den billige russiske gas videre til øvrige dele af Europa.Nord Stream 1 er en 1.224 kilometer lang gasrørledning, som løber fra Rusland til Tyskland under Østersøen. Den har været i brug siden 2011.Gaskrisen har fået Tyskland til desperat at lede efter alternativer til gas til landets vigtige industri men også til private husholdninger. For eksempel ved at skifte over til den allermest forurenende energikilde. Nemlig kul. DR Nyheders korrespondent i Tyskland har været i Leipzig for at møde en kulhandler, der har kronede dage:FAKTABOKS om Nord Stream 1•Nord Stream 1 er 1224 kilometer lang og består af to gasrørledninger, som løber under Østersøen.•De strækker sig fra Vyborg i Rusland til Lubmin i det nordøstlige Tyskland. Derfra transporteres gassen videre til øvrige dele af Europa.•Den har været i brug siden 2011 og har dermed i over et årti - indtil Ruslands krig mod Ukraine - været en pålidelig kilde til gas til Europa.•Den kan transportere 55 milliarder kubikmeter gas om året til Europa. Det er nok til at forsyne cirka 26 millioner europæiske hjem. Dermed er den særdeles vigtig for gasforsyningen til Europa.•Ruslands statsejede gasselskab Gazprom ejer 51 procent af Nord Stream 1. Tysklands EON og Wintershall Dea, hollandske Gasunie og Frankrigs Engie er også aktionærer.•Projektet er længe blevet set som en model for økonomisk samarbejde mellem Rusland og EU, hvor lande som Tyskland og Italien er blevet stærkt afhængige af den billige russiske gas.•Rusland er verdens største eksportør af naturgas. Europa importerer omkring 40 procent af sin gas fra Rusland.•Kilder: AFP og Reuters af /ritzau/'

### Exercise

In [133]:
url = 'https://www.basketball-reference.com/leagues/NBA_2018.html' 
response = requests.get(url, headers={'name':'Siyi','email':'wasariii@outlook.com'})
soup = BeautifulSoup(response.content,'lxml')
table_node = soup.find('div', class_ = 'table_wrapper')


print(table_node)

<div class="table_wrapper" id="all_confs_standings_E">
<div class="section_heading assoc_confs_standings_E" id="confs_standings_E_sh">
<span class="section_anchor" data-label="Conference Standings" id="confs_standings_E_link"></span><h2>Conference Standings</h2> <div class="section_heading_text">
<ul><li><small>* Playoff teams</small></li>
</ul>
</div>
</div>
<div class="table_container" id="div_confs_standings_E">
<table class="suppress_all sortable stats_table" data-cols-to-freeze=",1" id="confs_standings_E">
<caption>Conference Standings Table</caption>
<colgroup><col/><col/><col/><col/><col/><col/><col/><col/></colgroup>
<thead>
<tr>
<th aria-label="Eastern Conference" class="poptip sort_default_asc left" data-stat="team_name" scope="col">Eastern Conference</th>
<th aria-label="Wins" class="poptip right" data-stat="wins" data-tip="Wins" scope="col">W</th>
<th aria-label="Losses" class="poptip right" data-stat="losses" data-tip="Losses" scope="col">L</th>
<th aria-label="Win-Loss Percentage" class="poptip right" data-stat="win_loss_pct" data-tip="Win-Loss Percentage" scope="col">W/L%</th>
<th aria-label="GB" class="poptip sort_default_asc right" data-stat="gb" data-tip="Games Behind" scope="col">GB</th>
<th aria-label="Points Per Game" class="poptip right" data-stat="pts_per_g" data-tip="Points Per Game" scope="col">PS/G</th>
<th aria-label="Opponent Points Per Game" class="poptip right" data-stat="opp_pts_per_g" data-tip="Opponent Points Per Game" scope="col">PA/G</th>
<th aria-label="Simple Rating System" class="poptip right" data-stat="srs" data-tip="Simple Rating System; a team rating that takes into account average point differential and strength of schedule. The rating is denominated in points above/below average, where zero is average." scope="col">SRS</th>
</tr>
</thead>
<tbody><tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/TOR/2018.html">Toronto Raptors</a>*</th><td class="right" data-stat="wins">59</td><td class="right" data-stat="losses">23</td><td class="right" data-stat="win_loss_pct">.720</td><td class="right" data-stat="gb">—</td><td class="right" data-stat="pts_per_g">111.7</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">7.29</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BOS/2018.html">Boston Celtics</a>*</th><td class="right" data-stat="wins">55</td><td class="right" data-stat="losses">27</td><td class="right" data-stat="win_loss_pct">.671</td><td class="right" data-stat="gb">4.0</td><td class="right" data-stat="pts_per_g">104.0</td><td class="right" data-stat="opp_pts_per_g">100.4</td><td class="right" data-stat="srs">3.23</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/PHI/2018.html">Philadelphia 76ers</a>*</th><td class="right" data-stat="wins">52</td><td class="right" data-stat="losses">30</td><td class="right" data-stat="win_loss_pct">.634</td><td class="right" data-stat="gb">7.0</td><td class="right" data-stat="pts_per_g">109.8</td><td class="right" data-stat="opp_pts_per_g">105.3</td><td class="right" data-stat="srs">4.30</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CLE/2018.html">Cleveland Cavaliers</a>*</th><td class="right" data-stat="wins">50</td><td class="right" data-stat="losses">32</td><td class="right" data-stat="win_loss_pct">.610</td><td class="right" data-stat="gb">9.0</td><td class="right" data-stat="pts_per_g">110.9</td><td class="right" data-stat="opp_pts_per_g">109.9</td><td class="right" data-stat="srs">0.59</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/IND/2018.html">Indiana Pacers</a>*</th><td class="right" data-stat="wins">48</td><td class="right" data-stat="losses">34</td><td class="right" data-stat="win_loss_pct">.585</td><td class="right" data-stat="gb">11.0</td><td class="right" data-stat="pts_per_g">105.6</td><td class="right" data-stat="opp_pts_per_g">104.2</td><td class="right" data-stat="srs">1.18</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIA/2018.html">Miami Heat</a>*</th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">102.9</td><td class="right" data-stat="srs">0.15</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIL/2018.html">Milwaukee Bucks</a>*</th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">106.5</td><td class="right" data-stat="opp_pts_per_g">106.8</td><td class="right" data-stat="srs">-0.45</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/WAS/2018.html">Washington Wizards</a>*</th><td class="right" data-stat="wins">43</td><td class="right" data-stat="losses">39</td><td class="right" data-stat="win_loss_pct">.524</td><td class="right" data-stat="gb">16.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">106.0</td><td class="right" data-stat="srs">0.53</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/DET/2018.html">Detroit Pistons</a></th><td class="right" data-stat="wins">39</td><td class="right" data-stat="losses">43</td><td class="right" data-stat="win_loss_pct">.476</td><td class="right" data-stat="gb">20.0</td><td class="right" data-stat="pts_per_g">103.8</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">-0.26</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHO/2018.html">Charlotte Hornets</a></th><td class="right" data-stat="wins">36</td><td class="right" data-stat="losses">46</td><td class="right" data-stat="win_loss_pct">.439</td><td class="right" data-stat="gb">23.0</td><td class="right" data-stat="pts_per_g">108.2</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">0.07</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/NYK/2018.html">New York Knicks</a></th><td class="right" data-stat="wins">29</td><td class="right" data-stat="losses">53</td><td class="right" data-stat="win_loss_pct">.354</td><td class="right" data-stat="gb">30.0</td><td class="right" data-stat="pts_per_g">104.5</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">-3.53</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BRK/2018.html">Brooklyn Nets</a></th><td class="right" data-stat="wins">28</td><td class="right" data-stat="losses">54</td><td class="right" data-stat="win_loss_pct">.341</td><td class="right" data-stat="gb">31.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">110.3</td><td class="right" data-stat="srs">-3.67</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHI/2018.html">Chicago Bulls</a></th><td class="right" data-stat="wins">27</td><td class="right" data-stat="losses">55</td><td class="right" data-stat="win_loss_pct">.329</td><td class="right" data-stat="gb">32.0</td><td class="right" data-stat="pts_per_g">102.9</td><td class="right" data-stat="opp_pts_per_g">110.0</td><td class="right" data-stat="srs">-6.84</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ORL/2018.html">Orlando Magic</a></th><td class="right" data-stat="wins">25</td><td class="right" data-stat="losses">57</td><td class="right" data-stat="win_loss_pct">.305</td><td class="right" data-stat="gb">34.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.2</td><td class="right" data-stat="srs">-4.92</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ATL/2018.html">Atlanta Hawks</a></th><td class="right" data-stat="wins">24</td><td class="right" data-stat="losses">58</td><td class="right" data-stat="win_loss_pct">.293</td><td class="right" data-stat="gb">35.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.8</td><td class="right" data-stat="srs">-5.30</td></tr>
</tbody></table>
</div>
</div>

In [134]:
# 定义函数从上面的结果中制作Data Frame
def parse_html_table(table_node):
    # Get the columns in a list
    columns_html = table_node.thead.find_all('th')
    # Extract the text
    columns = [col.text for col in columns_html]

    rows_list = table_node.tbody.find_all('tr')

    data = []
    for row_node in rows_list:
        row = []
        for child in row_node.children:
            row.append(child.text)
        data.append(row)
    df = pd.DataFrame(data,columns=columns)
    return df
df = parse_html_table(table_node)
df

      Eastern Conference   W   L  W/L%    GB   PS/G   PA/G    SRS
0       Toronto Raptors*  59  23  .720     —  111.7  103.9   7.29
1        Boston Celtics*  55  27  .671   4.0  104.0  100.4   3.23
2    Philadelphia 76ers*  52  30  .634   7.0  109.8  105.3   4.30
3   Cleveland Cavaliers*  50  32  .610   9.0  110.9  109.9   0.59
4        Indiana Pacers*  48  34  .585  11.0  105.6  104.2   1.18
5            Miami Heat*  44  38  .537  15.0  103.4  102.9   0.15
6       Milwaukee Bucks*  44  38  .537  15.0  106.5  106.8  -0.45
7    Washington Wizards*  43  39  .524  16.0  106.6  106.0   0.53
8        Detroit Pistons  39  43  .476  20.0  103.8  103.9  -0.26
9      Charlotte Hornets  36  46  .439  23.0  108.2  108.0   0.07
10       New York Knicks  29  53  .354  30.0  104.5  108.0  -3.53
11         Brooklyn Nets  28  54  .341  31.0  106.6  110.3  -3.67
12         Chicago Bulls  27  55  .329  32.0  102.9  110.0  -6.84
13         Orlando Magic  25  57  .305  34.0  103.4  108.2  -4.92
14         Atlanta Hawks  24  58  .293  35.0  103.4  108.8  -5.30

In [162]:
tables = soup.find_all('table') #Locate all table nodes

dfs = []
for i in range(10): #"len(tables)" instead of 3 to get all tables. len(tables)=13，目前列不全
    table = parse_html_table(tables[i]) #Apply parse_html_table function
    dfs.append(table) # store table in a list
dfs[9]

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Boston Celtics*,82,19805,38.7,88.0,.440,9.7,28.6,.339,...,.763,10.0,35.4,45.4,22.0,7.5,4.6,14.6,19.8,103.9
1,2,Utah Jazz*,82,19755,38.8,86.4,.449,9.9,27.0,.365,...,.771,9.0,34.3,43.3,20.8,8.6,4.8,15.5,21.4,103.9
2,3,San Antonio Spurs*,82,19730,40.1,88.5,.453,9.6,27.6,.348,...,.759,9.7,35.0,44.6,22.9,8.0,4.1,14.8,20.7,104.8
3,4,Philadelphia 76ers*,82,19780,37.9,87.4,.434,10.1,29.5,.342,...,.745,9.9,32.1,42.1,21.7,8.5,5.1,14.3,20.3,105.0
4,5,Toronto Raptors*,82,19830,39.1,87.2,.449,9.1,25.4,.357,...,.767,10.0,33.2,43.2,22.2,7.3,5.0,14.6,20.3,105.9
5,6,Houston Rockets*,82,19755,40.4,87.4,.462,10.3,29.5,.351,...,.746,8.8,34.1,42.9,22.9,7.6,4.5,14.9,20.8,106.1
6,7,Miami Heat*,82,19930,38.9,86.6,.450,9.9,27.5,.360,...,.783,9.4,35.2,44.5,21.7,7.8,4.8,14.6,20.0,106.3
7,8,Portland Trail Blazers*,82,19755,39.6,88.7,.447,10.0,27.4,.364,...,.755,9.6,34.7,44.3,20.8,7.6,5.3,13.0,19.7,106.4
8,9,Oklahoma City Thunder*,82,19830,39.5,86.2,.458,11.5,31.4,.367,...,.769,9.8,33.5,43.3,23.9,7.9,4.7,16.5,21.9,107.2
9,10,Detroit Pistons,82,19805,40.4,88.0,.459,11.4,31.8,.359,...,.776,9.5,35.7,45.2,26.0,7.5,5.0,15.3,19.0,107.3
10,11,Golden State Warriors*,82,19730,40.3,90.1,.447,10.4,29.2,.357,...,.758,10.9,31.7,42.6,23.6,8.8,3.7,14.4,18.5,107.6
11,12,Los Angeles Lakers,82,19905,40.4,88.6,.456,10.3,29.7,.346,...,.761,10.1,34.1,44.2,23.2,8.2,5.4,14.1,20.2,108.0
12,13,Indiana Pacers*,82,19755,40.9,88.0,.465,11.0,31.6,.349,...,.757,10.6,34.0,44.6,24.1,7.3,5.4,16.1,19.2,108.1
13,14,New Orleans Pelicans*,82,19955,40.9,90.2,.454,10.7,30.0,.355,...,.784,10.6,34.0,44.6,23.3,8.0,4.1,14.2,20.0,108.3
14,15,Washington Wizards*,82,19855,40.0,86.5,.462,10.4,29.9,.349,...,.761,10.1,33.5,43.6,22.9,8.0,4.8,15.3,20.5,108.7
15,16,Charlotte Hornets,82,19780,41.5,88.8,.468,11.4,30.4,.375,...,.795,8.5,35.6,44.2,25.0,6.7,5.0,13.7,22.7,109.1
16,17,Dallas Mavericks,82,19805,40.8,87.1,.469,11.1,30.6,.363,...,.757,9.2,38.4,47.5,24.4,7.5,4.7,14.3,20.3,109.5
17,18,Milwaukee Bucks*,82,19830,40.4,86.3,.468,10.4,28.0,.372,...,.783,10.3,33.8,44.0,24.4,7.4,4.6,16.1,20.5,110.1
18,19,Orlando Magic,82,19730,41.6,89.0,.468,10.2,28.0,.362,...,.773,10.8,35.9,46.6,24.8,7.9,5.0,14.5,19.3,110.1
19,20,Los Angeles Clippers,82,19705,40.7,88.8,.458,10.9,30.6,.356,...,.782,10.7,33.4,44.1,24.9,8.6,5.7,14.2,22.2,110.2
20,21,Atlanta Hawks,82,19705,41.3,88.1,.469,11.8,31.2,.377,...,.772,10.4,34.5,44.9,26.5,8.8,5.6,15.3,20.6,110.6
21,22,Brooklyn Nets,82,19855,41.8,89.7,.466,9.1,24.6,.369,...,.766,10.4,36.4,46.9,21.8,7.7,5.5,12.4,19.7,110.6
22,23,New York Knicks,82,19830,40.4,88.5,.457,11.5,31.2,.368,...,.774,10.5,33.8,44.2,24.6,8.4,4.9,13.7,18.9,110.7
23,24,Chicago Bulls,82,19855,41.3,87.5,.472,12.2,32.9,.370,...,.787,8.5,37.5,46.0,26.1,7.2,5.2,13.7,17.5,110.9
24,25,Memphis Grizzlies,82,19705,39.1,84.5,.462,11.2,30.5,.368,...,.769,10.0,34.7,44.7,23.3,8.5,5.4,15.5,21.5,111.0
25,26,Denver Nuggets,82,19880,42.2,88.7,.476,11.1,29.5,.378,...,.738,10.0,32.6,42.6,25.3,8.2,4.9,14.1,21.2,111.0
26,27,Minnesota Timberwolves*,82,19805,41.6,87.6,.475,11.2,30.7,.366,...,.779,10.1,33.2,43.3,24.8,6.7,4.8,15.6,21.6,111.1
27,28,Sacramento Kings,82,19755,40.7,86.5,.470,12.5,33.1,.377,...,.765,9.5,36.4,45.9,24.8,8.1,5.0,15.1,18.2,111.1
28,29,Cleveland Cavaliers*,82,19730,42.6,89.9,.474,11.9,32.2,.368,...,.756,10.1,34.3,44.4,26.3,7.6,4.2,13.7,21.1,111.9
29,30,Phoenix Suns,82,19705,41.6,88.4,.471,10.9,29.1,.373,...,.766,10.4,35.3,45.7,23.2,8.6,5.9,13.3,20.8,112.8

In [175]:
# pd.read_html的作用：Read HTML tables into a list of DataFrame objects.
a = pd.read_html(url)
a[12]  # 这个方法能列出全部的表

   Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Rk                     Team                  G
0                 1.0            Atlanta Hawks                 82
1                 2.0          Boston Celtics*                 82
2                 3.0            Brooklyn Nets                 82
3                 4.0            Chicago Bulls                 82
4                 5.0        Charlotte Hornets                 82
5                 6.0     Cleveland Cavaliers*                 82
6                 7.0         Dallas Mavericks                 82
7                 8.0           Denver Nuggets                 82
8                 9.0          Detroit Pistons                 82
9                10.0   Golden State Warriors*                 82
10               11.0         Houston Rockets*                 82
11               12.0          Indiana Pacers*                 82
12               13.0     Los Angeles Clippers                 82
13               14.0       Los Angeles Lakers                 82
14               15.0        Memphis Grizzlies                 82
15               16.0              Miami Heat*                 82
16               17.0         Milwaukee Bucks*                 82
17               18.0  Minnesota Timberwolves*                 82
18               19.0    New Orleans Pelicans*                 82
19               20.0          New York Knicks                 82
20               21.0   Oklahoma City Thunder*                 82
21               22.0            Orlando Magic                 82
22               23.0      Philadelphia 76ers*                 82
23               24.0             Phoenix Suns                 82
24               25.0  Portland Trail Blazers*                 82
25               26.0         Sacramento Kings                 82
26               27.0       San Antonio Spurs*                 82
27               28.0         Toronto Raptors*                 82
28               29.0               Utah Jazz*                 82
29               30.0      Washington Wizards*                 82
30                NaN           League Average                 82

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                   MP                FG%              Dist.
0               19705              0.469               13.7
1               19805              0.440               13.1
2               19855              0.466               12.6
3               19855              0.472               13.7
4               19780              0.468               13.7
5               19730              0.474               13.4
6               19805              0.469               13.8
7               19880              0.476               12.8
8               19805              0.459               13.6
9               19730              0.447               13.0
10              19755              0.462               12.8
11              19755              0.465               13.6
12              19705              0.458               13.4
13              19905              0.456               12.9
14              19705              0.462               13.3
15              19930              0.450               12.7
16              19830              0.468               12.5
17              19805              0.475               13.1
18              19955              0.454               13.3
19              19830              0.457               13.3
20              19830              0.458               13.1
21              19730              0.468               12.7
22              19780              0.434               13.6
23              19705              0.471               13.0
24              19755              0.447               12.9
25              19755              0.470               13.8
26              19730              0.453               12.8
27              19830              0.449               12.2
28              19755              0.449               13.1
29              19855              0.462               13.3
30              19795              0.460               13.2

   Unnamed: 6_level_0 % of FGA by Distance                ... % of FG Ast'd  \
   Unnamed: 6_level_1                   2P    0-3   3-10  ...            3P
0                 NaN                0.646  0.271  0.127  ...         0.872
1                 NaN                0.674  0.286  0.162  ...         0.818
2                 NaN                0.726  0.260  0.185  ...         0.780
3                 NaN                0.624  0.292  0.122  ...         0.864
4                 NaN                0.657  0.262  0.144  ...         0.853
5                 NaN                0.641  0.299  0.132  ...         0.832
6                 NaN                0.649  0.238  0.167  ...         0.826
7                 NaN                0.668  0.268  0.191  ...         0.835
8                 NaN                0.638  0.251  0.177  ...         0.904
9                 NaN                0.676  0.278  0.166  ...         0.802
10                NaN                0.663  0.304  0.157  ...         0.802
11                NaN                0.641  0.285  0.138  ...         0.861
12                NaN                0.656  0.279  0.139  ...         0.806
13                NaN                0.665  0.304  0.156  ...         0.806
14                NaN                0.639  0.296  0.131  ...         0.833
15                NaN                0.683  0.279  0.188  ...         0.820
16                NaN                0.676  0.327  0.145  ...         0.848
17                NaN                0.650  0.297  0.141  ...         0.840
18                NaN                0.667  0.278  0.155  ...         0.833
19                NaN                0.648  0.291  0.142  ...         0.848
20                NaN                0.636  0.302  0.144  ...         0.842
21                NaN                0.685  0.280  0.180  ...         0.834
22                NaN                0.662  0.239  0.176  ...         0.807
23                NaN                0.670  0.306  0.133  ...         0.817
24                NaN                0.691  0.281  0.152  ...         0.819
25                NaN                0.617  0.260  0.166  ...         0.828
26                NaN                0.688  0.281  0.161  ...         0.827
27                NaN                0.708  0.298  0.177  ...         0.813
28                NaN                0.687  0.254  0.179  ...         0.801
29                NaN                0.654  0.279  0.154  ...         0.808
30                NaN                0.663  0.281  0.156  ...         0.830

   Unnamed: 23_level_0  Dunks      Unnamed: 26_level_0 Layups        \
   Unnamed: 23_level_1   %FGA  Md. Unnamed: 26_level_1   %FGA   Md.
0                  NaN  0.051  318                 NaN  0.259  1024
1                  NaN  0.046  294                 NaN  0.286  1094
2                  NaN  0.043  275                 NaN  0.277  1080
3                  NaN  0.051  330                 NaN  0.264  1110
4                  NaN  0.049  314                 NaN  0.258  1064
5                  NaN  0.055  362                 NaN  0.276  1148
6                  NaN  0.051  314                 NaN  0.216   855
7                  NaN  0.049  310                 NaN  0.291  1188
8                  NaN  0.046  288                 NaN  0.271  1059
9                  NaN  0.052  347                 NaN  0.274  1089
10                 NaN  0.050  315                 NaN  0.294  1193
11                 NaN  0.055  340                 NaN  0.270  1073
12                 NaN  0.058  372                 NaN  0.252  1027
13                 NaN  0.059  384                 NaN  0.280  1142
14                 NaN  0.059  353                 NaN  0.268   993
15                 NaN  0.050  307                 NaN  0.273   995
16                 NaN  0.058  349                 NaN  0.316  1189
17                 NaN  0.060  392                 NaN  0.273  1112
18                 NaN  0.056  376                 NaN  0.277  1129
19                 NaN  0.059  359                 NaN  0.271  1016
20                 NaN  0.059  349                 NaN  0.270  1020
21                 NaN  0.057  365                 NaN  0.296  1189
22                 NaN  0.049  315                 NaN  0.255   936
23                 NaN  0.054  352                 NaN  0.277  1126
24                 NaN  0.037  219                 NaN  0.267   976
25                 NaN  0.052  319                 NaN  0.271  1037
26                 NaN  0.055  337                 NaN  0.267   968
27                 NaN  0.050  300                 NaN  0.287  1039
28                 NaN  0.052  316                 NaN  0.260   943
29                 NaN  0.055  355                 NaN  0.286  1118
30                 NaN  0.053  331                 NaN  0.273  1064

   Unnamed: 29_level_0 Corner
   Unnamed: 29_level_1   %3PA    3P%
0                  NaN  0.216  0.381
1                  NaN  0.181  0.417
2                  NaN  0.186  0.401
3                  NaN  0.213  0.393
4                  NaN  0.194  0.418
5                  NaN  0.213  0.446
6                  NaN  0.190  0.384
7                  NaN  0.247  0.390
8                  NaN  0.233  0.387
9                  NaN  0.189  0.378
10                 NaN  0.214  0.380
11                 NaN  0.198  0.397
12                 NaN  0.233  0.387
13                 NaN  0.196  0.364
14                 NaN  0.223  0.425
15                 NaN  0.199  0.363
16                 NaN  0.222  0.417
17                 NaN  0.228  0.374
18                 NaN  0.201  0.379
19                 NaN  0.243  0.405
20                 NaN  0.239  0.402
21                 NaN  0.230  0.426
22                 NaN  0.187  0.385
23                 NaN  0.190  0.401
24                 NaN  0.186  0.405
25                 NaN  0.205  0.405
26                 NaN  0.213  0.358
27                 NaN  0.196  0.363
28                 NaN  0.183  0.404
29                 NaN  0.192  0.364
30                 NaN  0.208  0.394

[31 rows x 32 columns]